# train.py
import torch
from torch.utils.data import DataLoader
import os
import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import argparse

# 引入你的模組
from utils.weather_dataloader import WeatherSegmentationDataset
from weather_trainer import WeatherSAMTrainer
from segment_anything.build_weather_sam import build_weather_sam_vit_h, build_weather_sam_vit_b

def plot_history(history, output_dir):
    """繪製訓練曲線"""
    if not history:
        return
    df = pd.DataFrame(history)
    plt.figure(figsize=(12, 6))
    
    plt.plot(df['epoch'], df['train_total'], 'b-o', label='Train Total', linewidth=2)
    plt.plot(df['epoch'], df['val_total'], 'r-s', label='Val Total', linewidth=2)
    
    if 'train_dice' in df.columns and 'val_dice' in df.columns:
        plt.plot(df['epoch'], df['train_dice'], 'g--', label='Train Dice', alpha=0.6)
        plt.plot(df['epoch'], df['val_dice'], 'm--', label='Val Dice', alpha=0.6)
    
    plt.xlabel('Epoch')
    plt.ylabel('Loss Value')
    plt.title('WeatherSAM Training Curve')
    plt.legend()
    plt.grid(True, linestyle='--', alpha=0.7)
    plt.savefig(os.path.join(output_dir, 'loss_curve.png'))
    plt.close()
    print(f"📉 Loss curve updated at: {os.path.join(output_dir, 'loss_curve.png')}")

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--device", type=str, default="cuda" if torch.cuda.is_available() else "cpu")
    parser.add_argument("--checkpoint", type=str, default="checkpoints/sam_vit_h_4b8939.pth", help="Path to SAM checkpoint")
    parser.add_argument("--model_type", type=str, default="vit_h", choices=["vit_b", "vit_h"])
    
    # 修改：建議使用者優先使用 cached CSV
    parser.add_argument("--train_csv", type=str, default="data/weather_dataset/train_cached.csv", 
                        help="Path to train CSV. Use the '_cached.csv' generated by precompute_features.py for speed.")
    parser.add_argument("--val_csv", type=str, default="data/weather_dataset/val_cached.csv", 
                        help="Path to val CSV.")
    
    parser.add_argument("--batch_size", type=int, default=2)
    parser.add_argument("--epochs", type=int, default=20)
    parser.add_argument("--lr", type=float, default=1e-4)
    parser.add_argument("--output_dir", type=str, default="outputs_weather_sam")
    
    args = parser.parse_args()
    
    os.makedirs(args.output_dir, exist_ok=True)

    print(f"🚀 Start Training WeatherSAM ({args.model_type})...")
    print(f"   Train CSV: {args.train_csv}")
    
    # 1. 建立模型
    print("🏗️  Building model...")
    if args.model_type == "vit_h":
        model = build_weather_sam_vit_h(checkpoint=args.checkpoint)
    else:
        model = build_weather_sam_vit_b(checkpoint=args.checkpoint)
    
    # 2. 準備 DataLoader
    print("📂 Preparing data...")
    
    # 檢查 CSV 是否存在，若無 Cached 版本則退回原始版本
    if not os.path.exists(args.train_csv) and "_cached" in args.train_csv:
        print(f"⚠️ Cached CSV not found. Falling back to non-cached version...")
        args.train_csv = args.train_csv.replace("_cached.csv", ".csv")
        
    if not os.path.exists(args.val_csv) and "_cached" in args.val_csv:
        args.val_csv = args.val_csv.replace("_cached.csv", ".csv")

    train_ds = WeatherSegmentationDataset(csv_file=args.train_csv, mode='train')
    
    if os.path.exists(args.val_csv):
        val_ds = WeatherSegmentationDataset(csv_file=args.val_csv, mode='val')
    else:
        print(f"⚠️ Warning: Validation CSV not found. Using Train set for validation.")
        val_ds = WeatherSegmentationDataset(csv_file=args.train_csv, mode='val')

    # DataLoader 設定
    train_loader = DataLoader(
        train_ds, 
        batch_size=args.batch_size, 
        shuffle=True, 
        num_workers=4,
        collate_fn=WeatherSegmentationDataset.collate_fn,
        pin_memory=True,
        persistent_workers=True # ⚡ 加速：避免每個 epoch 重新創建 worker
    )
    
    val_loader = DataLoader(
        val_ds, 
        batch_size=args.batch_size, 
        shuffle=False, 
        num_workers=4,
        collate_fn=WeatherSegmentationDataset.collate_fn,
        pin_memory=True,
        persistent_workers=True
    )
    
    # 3. 初始化 Trainer
    print("⚙️  Initializing Trainer...")
    trainer = WeatherSAMTrainer(
        model=model,
        train_loader=train_loader,
        val_loader=val_loader,
        device=args.device,
        lr=args.lr
    )

    # 4. 訓練迴圈
    best_val_loss = float('inf')
    history = []

    print(f"🔥 Start training loop for {args.epochs} epochs")
    
    for epoch in range(args.epochs):
        train_metrics = trainer.train_epoch(epoch)
        val_metrics = trainer.validate_epoch(epoch)
        
        log_entry = {
            "epoch": epoch + 1,
            "train_total": train_metrics["total"],
            "train_dice": train_metrics["dice"],
            "val_total": val_metrics["total"],
            "val_dice": val_metrics["dice"]
        }
        history.append(log_entry)
        
        print(f"   [Epoch {epoch+1}] Train Loss: {train_metrics['total']:.4f} | Val Loss: {val_metrics['total']:.4f}")
        
        # 存檔與繪圖
        pd.DataFrame(history).to_csv(os.path.join(args.output_dir, "train_log.csv"), index=False)
        plot_history(history, args.output_dir)
        
        # 儲存最佳模型
        if val_metrics['total'] < best_val_loss:
            best_val_loss = val_metrics['total']
            save_path = os.path.join(args.output_dir, "weather_sam_best.pth")
            trainer.save_checkpoint(save_path)
            print(f"   🏆 New best model saved!")
            
        if (epoch + 1) % 5 == 0:
            save_path = os.path.join(args.output_dir, f"weather_sam_epoch_{epoch+1}.pth")
            trainer.save_checkpoint(save_path)

    print("\n✅ Training completed!")

if __name__ == "__main__":
    main()